# Generated by Django 4.0.8 on 2022-11-12 16:28

from django.db import migrations, models
import fort_worth_crawler.shared.defaults
import fort_worth_crawler.shared.fields
import fort_worth_crawler.shared.paths
import functools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('repository_unique_id', models.CharField(max_length=1024, unique=True)),
                ('repository_url', models.CharField(max_length=1024)),
                ('repository_folder_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('tagged_counterparty', models.CharField(blank=True, max_length=1024, null=True)),
                ('custom_meta', fort_worth_crawler.shared.defaults.NullableJSONField(default=fort_worth_crawler.shared.fields.jsonfield_default_value, null=True)),
                ('first_scraped', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('pdf_file', models.FileField(max_length=1024, upload_to=functools.partial(fort_worth_crawler.shared.paths.calc_pdf_file_path, *(), **{'sub_folder': 'pdf_files'}))),
            ],
        ),
    ]
