# Generated by Django 4.0.8 on 2022-11-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='local_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='document',
            name='repository_unique_id',
            field=models.CharField(max_length=1024),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('repository_unique_id', 'local_version'), name='unique_1'),
        ),
    ]
