# Generated by Django 4.0.8 on 2022-11-13 20:51

from django.db import migrations, models
import django.utils.timezone
import fort_worth_crawler.shared.defaults
import fort_worth_crawler.shared.fields


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_local_version_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='last_updated',
            new_name='last_updated_locally',
        ),
        migrations.AddField(
            model_name='document',
            name='last_updated_on_remote',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='source_json',
            field=fort_worth_crawler.shared.defaults.NullableJSONField(default=fort_worth_crawler.shared.fields.jsonfield_default_value),
        ),
        migrations.AlterField(
            model_name='document',
            name='repository_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
